config/routes.rb
Factory::Application.routes.draw do

  devise_for :users, :skip => [:registrations, :sessions], :controllers => {:invitations => 'users/invitations', :registrations => 'users/registrations'}
  
  get "pages/enter"
  
  as :user do
    get "/login" => "devise/sessions#new", :as => :new_user_session
    post "/login" => "devise/sessions#create", :as => :user_session
    get "/logout" => "devise/sessions#destroy", :as => :destroy_user_session
    get "signup" => "devise/registrations#new", :as => :new_user_registration
    put "update-registration" => "users/registrations#update", :as => :user_registration
    delete "delete-registration" => "users/registrations#destroy", :as => :delete_user_registration
    get "edit-registration" => "users/registrations#edit", :as => :edit_user_registration
    get "cancel-registration" => "users/registrations#cancel", :as => :cancel_user_registration      
  end

  match 'users/:id' => 'users#destroy', :via => :delete, :as => :delete_user
	
	resources :users
  resources :imports
  resources :memberships

  resources :analyses do   
    post 'bulk_delete', :on => :collection    
  end

  resources :categories do
    collection { post :sort}
    post 'bulk_delete', :on => :collection
  end

  resources :properties do
    collection { post :sort}    
    post 'bulk_delete', :on => :collection
    collection {post :import}    
  end

  resources :items do
    post 'bulk_delete', :on => :collection
    resources :specifications
    collection {post :import}
  end

  resources :specifications do
    get 'display', :on => :collection
    get 'new_import', :on => :collection
    collection {post :save_import}
  end
  
  resources :tenants do
    get 'count', :on => :collection
    get 'set', :on => :member
  end

  resources :imports do
    collection {get :import}
  end

  match 'specifications/:id/cancel' => 'specifications#cancel', :as => :cancel_specification
  match 'specifications/:id/copy' => 'specifications#copy', :as => :copy_specification
  match 'specifications/:id/paste' => 'specifications#paste', :as => :paste_specification
  match 'specifications/:id/notes' => 'specifications#notes', :as => :notes
  match 'items/:id/copy' => 'items#copy', :as => :copy_item
  match 'analyses/:id/instructions' => 'analyses#instructions'
  match 'imports/help' => 'imports#help', :as => :import_help
  match 'about' => 'pages#about', :as => :about

  root :to => 'pages#enter'
  
end

app/models/membership.rb
class Membership < ActiveRecord::Base
  belongs_to :tenant
  belongs_to :user
  belongs_to :role
  accepts_nested_attributes_for :user, :role
  attr_accessible :tenant_id, :user_id, :role_id

  
end

app/controllers/memberships_controller.rb
class MembershipsController < ApplicationController
	load_and_authorize_resource

	def new
		@tenant = current_tenant
		@membership = Membership.new(:tenant_id => @tenant.id)
	end

	def create
		@membership = Membership.new(params[:membership])
		@membership.save
	end

	def show
	end

	def index
		@is_table = true
		@membership = Membership.where("user_id = ? AND tenant_id = ?", @current_user.id, @current_tenant.id).first
		@role = @membership.role
		@tenants = Tenant.where("membership.role_name = ?", "owner")
		@memberships = Membership.where(tenant_id: current_tenant.id).joins(:tenant, :user, :role).order("display_order, tenants.name, users.email")
	end

	def edit
		@membership = Membership.find(params[:id])
	end

	def update
		@membership = Membership.find(params[:id])
		if @membership.update_attributes(params[:membership])
			flash[:success] = "#{@membership.user.email} role changed to #{@membership.role.role_name}"
			redirect_to memberships_path
		else
			render :action => :edit
		end
	end

	def destroy
		@tenant = current_tenant
		@membership = Membership.find(params[:id])
		if @membership.destroy
			flash[:success] = "Membership deleted"
			redirect_to :back
		end
	end

	def destroy_user
		@user = User.find(params[:user_id])
		@email = @user.email
		if @user.destroy
			flash[:success] = "#{@email} deleted"
			redirect_to :back
		end
	end

end

app/views/memberships/edit.html.erb
<% set_title "#{@membership.tenant.name} - #{@membership.user.email}", prefix: "Edit ", suffix: " Membership" %>

<% set_width(6, 10) %>

<%= form_for @membership do |f| %>
	<%= render 'layouts/body/errors', :index => @membership %>
	
	<div class="form-group">
		<%= f.label :role %>
		<%= f.collection_select :role_id, Role.for_list, :id, :role_name, {}, :class => "form-control" %>
	</div>

	<div class="form-group">
		<%= f.submit 'Update', :class => 'btn btn-primary' %>
		<%= link_to 'Cancel', memberships_path, :class => "btn btn-default" %>
	</div>

<% end %>

app/views/memberships/index.html.erb
<% set_title "Users" %>

<% set_width(10, 12) %>

<% content_for :thead do %>

	<p><%= current_user.email %> : <%= current_tenant.name %> : <%= @role.role_name %></p>

		<tr>
			<th>User</th>
			<th>Company</th>
			<th>Role</th>
			<th>Edit</th>
		</tr>
<% end %>

<% content_for :table do %>
	
	<% @memberships.each do |m| %>
		<% if m.user == current_user || m.role.viewable %>
			<tr>
				<td><%= m.user.email %></td>
				<td><%= m.tenant.name %></td>
				<td><%= m.role.role_name %></td>
				<td>
					<% if m.role.role_name != "root" %>
						<%= link_to "Change role", edit_membership_path(m.id) %>
					<% end %>
					<% if m.role.role_name != "owner" && m.user != current_user %>
						<%= link_to "Remove user", m, :method => "delete", :style => "padding-left:15px", :confirm => "This will remove #{m.user.email} from #{m.tenant.name}" %>
					<% end %>
				</td>
			</tr>
		<% end %>
	<% end %>

<% end %>

<% content_for :footer do %>
	<% if can? :create, User %>
		<%= link_to "Invite new", new_user_invitation_path, :class => "btn btn-primary" %>
	<% end %>
<% end %>	