config/routes.rb
Factory::Application.routes.draw do

  devise_for :users, :skip => [:registrations, :sessions], :controllers => {:invitations => 'users/invitations', :registrations => 'users/registrations'}
  
  get "pages/enter"
  
  as :user do
    get "/login" => "devise/sessions#new", :as => :new_user_session
    post "/login" => "devise/sessions#create", :as => :user_session
    get "/logout" => "devise/sessions#destroy", :as => :destroy_user_session
    get "signup" => "devise/registrations#new", :as => :new_user_registration
    put "update-registration" => "users/registrations#update", :as => :user_registration
    delete "delete-registration" => "users/registrations#destroy", :as => :delete_user_registration
    get "edit-registration" => "users/registrations#edit", :as => :edit_user_registration
    get "cancel-registration" => "users/registrations#cancel", :as => :cancel_user_registration      
  end

  match 'users/:id' => 'users#destroy', :via => :delete, :as => :delete_user
	
	resources :users
  resources :imports
  resources :memberships

  resources :analyses do   
    post 'bulk_delete', :on => :collection    
  end

  resources :categories do
    collection { post :sort}
    post 'bulk_delete', :on => :collection
  end

  resources :properties do
    collection { post :sort}    
    post 'bulk_delete', :on => :collection
    collection {post :import}    
  end

  resources :items do
    post 'bulk_delete', :on => :collection
    resources :specifications
    collection {post :import}
  end

  resources :specifications do
    get 'display', :on => :collection
    get 'new_import', :on => :collection
    collection {post :save_import}
  end
  
  resources :tenants do
    get 'count', :on => :collection
    get 'set', :on => :member
  end

  resources :imports do
    collection {get :import}
  end

  match 'specifications/:id/cancel' => 'specifications#cancel', :as => :cancel_specification
  match 'specifications/:id/copy' => 'specifications#copy', :as => :copy_specification
  match 'specifications/:id/paste' => 'specifications#paste', :as => :paste_specification
  match 'specifications/:id/notes' => 'specifications#notes', :as => :notes
  match 'items/:id/copy' => 'items#copy', :as => :copy_item
  match 'analyses/:id/instructions' => 'analyses#instructions'
  match 'imports/help' => 'imports#help', :as => :import_help
  match 'about' => 'pages#about', :as => :about

  root :to => 'pages#enter'
  
end

app/models/property.rb
class Property  < ActiveRecord::Base
	validates :code, :presence => true, :uniqueness => {:scope => :tenant_id}
	validate :category_id_has_match
	has_many :specifications, :dependent => :destroy
	has_many :items, :through => :specifications
	belongs_to :category
	attr_accessible :code, :name, :display_order, :usl, :lsl, :label, :category_id
	accepts_nested_attributes_for :category
	default_scope { where(tenant_id: Tenant.current_id) }

	def self.import(file)
		CSV.foreach(file.path, headers: true) do |row|
			row['category_id'] = Category.where('code = (?)', row['category_id']).pluck(:id).first
			Property.create! row.to_hash
		end
	end

	private

	def category_id_has_match
		self.category_id && Category.exists?(self.category_id) || self.category_id.blank?
	end
	
end


app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
	include ApplicationHelper
	load_and_authorize_resource
	before_filter :find_properties
	before_filter :find_categories

	###### CRUD #######
	
	def new
		@property = Property.new()
	end
	
	def create
		@property = Property.new(params[:property])
		order = (params[:property][:display_order]).to_i
		# @property.reorder(order)
		if @property.save
			flash[:success] = "Property added"
			redirect_to properties_path
		else
			flash[:error] = "Property could not be added"
			redirect_to properties_path
		end
	end

  def index
  	@sortable_url = sort_properties_url
  	@layout_type = "fluid"
		@property = Property.new()
		@is_table = true
		@span = 8
	end

	def show
	end

  def edit
		@property = Property.find(params[:id])
		@is_edit_form = true
  end
	
	def update
		@property = Property.find(params[:id])
		if @property.update_attributes(params[:property])
			flash[:success] = "Property updated"
			redirect_to properties_path
		else
			render :action => :edit
		end
	end

	def destroy
		if Property.find(params[:id]).destroy		
			flash[:success] = 'Property deleted'
			redirect_to properties_path
		end
	end

	###### end of CRUD #######

	def bulk_delete
		Property.destroy(params[:deletions])
		redirect_to properties_path
	end

	def sort
		params[:property].each_with_index do |id, index|
			Property.update_all({display_order: index + 1}, {id: id})
		end
		render nothing: true
	end
	
	def find_properties
		@properties = Property.where(:deleted => false).order("display_order").paginate(:page => params[:page], :per_page => @per_page)
		@index = @properties
	end

	def find_categories
		@categories = Category.order(:display_order)
	end

	def import
		Property.import(params[:file])
		redirect_to properties_path
	end

end

app/helpers/properties_helper.rb
module PropertiesHelper

	def active_categories
		Category.where(:deleted => false)
	end
end

app/views/properties/_new.html.erb
<tr>
	<%= form_for(@property) do |f| %>
<!--		<div class="form-group"> -->		
			<td><%= f.collection_select :category_id, @categories, :id, :code, {:prompt => :true}, :class => "form-control input-sm" %></td>
			<td><%= f.text_field :code, :class => "form-control input-sm"  %></td>
			<td><%= f.text_field :name, :class => "form-control input-sm" %></td>
			<td><%= f.text_field :label, :class => "form-control input-sm" %></td>
			<td><%= f.submit "Add Property", :class => "btn btn-primary btn-sm" %></td>
			<td></td>
<!--		</div> -->			
	<% end %>		
</tr>

app/views/properties/edit.html.erb
<% set_title "#{@property.code}", prefix: "Edit ", suffix: " Property"%>

<% set_width(6, 10) %>

<%= form_for(@property) do |f| %>
	<%= render 'layouts/body/errors', :index => @property %>

	<div class="form-group">
		<%=f.label :code %>
		<%= f.text_field :code, :class => "form-control" %>
	</div>
	<div class="form-group">				
		<%=f.label :name, "Definition Name" %>
		<%= f.text_field :name, :class => "form-control" %>
	</div>
	<div class="form-group">
		<%=f.label :category_id %>
		<%= f.collection_select :category_id, @categories, :id, :code, {:include_blank => "Please select"}, :class => "form-control" %>
	</div>
	<div class="form-group">
		<%=f.label :label %>
		<%= f.text_field :label, :class => "form-control" %>
	</div>

	<div class="form-group">
		<%= f.submit :class => "btn btn-primary" %>
		<%= link_to 'Cancel', properties_path, :class => "btn btn-default" %>
	</div>
		
<% end %>

app/views/properties/index.html.erb
<% set_title "Properties"%>

<% set_width(12, 12) %>

<% content_for :thead do %>
	
		<tr>
			<th class="col-md-2">Category</th>
			<th class="col-md-2">Property Code</th>
			<th class="col-md-3">Property Name</th>
			<th class="col-md-3">Label</th>
			<th class="col-md-1"></th>
			<th class="col-md-1 center-block">						
				<%= link_to raw('<div class="glyphicon glyphicon-trash"></div>'), "#", :onclick => "$('.bulk_delete').submit()" %>				
			</th>
		</tr>
	
<% end %>
		
<% content_for :table do %>
	
	<tr>
		<%= render 'new' %>
	</tr>

	<%= form_tag bulk_delete_properties_path, :method => :bulk_delete, :class => "bulk_delete" do %>
		<% @properties.each do |t| %>
			<%= content_tag_for(:tr, t, class: "sortable") do %>
				<td><%= t.category_id  ? t.category.code : nil %></td>
				<td><%= t.code %></td>
				<td><%= t.name %></td>
				<td><%= t.label %></td>
				<td><div class="center-block"><%= link_to "Edit", edit_property_path(t) %></div></td>
				<td><div class="center-block"><%= check_box_tag "deletions[]", t.id %></div></td>
			<% end %>
		<% end %>
	<% end %>
	
<% end %>

<% content_for :import do %>	
		<%= form_tag import_properties_path, :multipart => true, :class => "form-horizontal top-space" do %>
			<div class="form-group">
				<label for="file" class="col-sm-3" >Import CSV File</label> 
				<%= file_field_tag :file, :class => "col-sm-6" %>
			
				<%= submit_tag "Import", :class => "btn btn-default col-sm-3" %>
			</div>
		<% end %>	
<% end %>

<% content_for :multi_view do %>
	<% @properties.each do |t| %>
		<div class="row">
			<div class="panel panel-default">
				<div class="panel-heading">				
					<strong class="panel-title text-muted"><%= t.code %></strong>
				</div>

				<div class="panel-body">						
					<div>
						<p class="text-muted col-xs-5">Name</p>
						<h4 class="col-xs-7"><%= t.name %></h4>
					</div>
				</div>
				<div class="panel-footer">
					
						<%= link_to "Edit", edit_item_path(t), :class => "btn btn-primary" %>
						
				</div>
				
			</div>
		</div>
	<% end %>
<% end %>