config/routes.rb
Factory::Application.routes.draw do

  devise_for :users, :skip => [:registrations, :sessions], :controllers => {:invitations => 'users/invitations', :registrations => 'users/registrations'}
  
  get "pages/enter"
  
  as :user do
    get "/login" => "devise/sessions#new", :as => :new_user_session
    post "/login" => "devise/sessions#create", :as => :user_session
    get "/logout" => "devise/sessions#destroy", :as => :destroy_user_session
    get "signup" => "devise/registrations#new", :as => :new_user_registration
    put "update-registration" => "users/registrations#update", :as => :user_registration
    delete "delete-registration" => "users/registrations#destroy", :as => :delete_user_registration
    get "edit-registration" => "users/registrations#edit", :as => :edit_user_registration
    get "cancel-registration" => "users/registrations#cancel", :as => :cancel_user_registration      
  end

  match 'users/:id' => 'users#destroy', :via => :delete, :as => :delete_user
	
	resources :users
  resources :imports
  resources :memberships

  resources :analyses do   
    post 'bulk_delete', :on => :collection    
  end

  resources :categories do
    collection { post :sort}
    post 'bulk_delete', :on => :collection
  end

  resources :properties do
    collection { post :sort}    
    post 'bulk_delete', :on => :collection
    collection {post :import}    
  end

  resources :items do
    post 'bulk_delete', :on => :collection
    resources :specifications
    collection {post :import}
  end

  resources :specifications do
    get 'display', :on => :collection
    get 'new_import', :on => :collection
    collection {post :save_import}
  end
  
  resources :tenants do
    get 'count', :on => :collection
    get 'set', :on => :member
  end

  resources :imports do
    collection {get :import}
  end

  match 'specifications/:id/cancel' => 'specifications#cancel', :as => :cancel_specification
  match 'specifications/:id/copy' => 'specifications#copy', :as => :copy_specification
  match 'specifications/:id/paste' => 'specifications#paste', :as => :paste_specification
  match 'specifications/:id/notes' => 'specifications#notes', :as => :notes
  match 'items/:id/copy' => 'items#copy', :as => :copy_item
  match 'analyses/:id/instructions' => 'analyses#instructions'
  match 'imports/help' => 'imports#help', :as => :import_help
  match 'about' => 'pages#about', :as => :about

  root :to => 'pages#enter'
  
end

app/models/specification.rb
class Specification < ActiveRecord::Base
	belongs_to :item
	belongs_to :property
	belongs_to :analysis
	delegate :category, :to => :property

	validates :item_id, :property_id, :presence => true
	validate :valid_eff_date?
	attr_accessible :property_id, :string_value, :text_value, :numeric_value, :usl, \
		:lsl, :unit_of_measure, :analysis_id, :eff_date, :item_id, :version, :tag, \
		:document_title, :document_url, :document_version, :deleted, :canceled, :notes

	before_save :default_values

	scope :active, where(:canceled => false, :deleted => false)

	def self.import(file)
		CSV.foreach(file.path, headers: true) do |row|
			item_code = row['item_id']
			row['item_id'] = Item.where('code = (?)', item_code).pluck(:id).first			
			property_code = row['property_id']
			row['property_id'] = Property.where('code = (?)', property_code).pluck(:id).first
			if !Specification.create row.to_hash
				logger.info "Error creating row #{row.inspect}"
			end
		end
	end

	def self.visible_by_item(item, visibility)
		stats = self.includes(:property => :category).where(:item_id => item)
			.order("categories.display_order, properties.display_order, eff_date DESC, version DESC")
		stats.select{|s| s if s.status == (visibility & s.status)}
	end

	def self.visible_by_property(property, visibility)
		stats = self.includes(:item).where(:property_id => property)
			.order("items.code, eff_date DESC, version DESC")
		stats.select{|s| s if s.status == (visibility & s.status)}
	end

	def status
		current_spec = Specification
			.where(["item_id = ? AND property_id = ? AND eff_date <= ? ", self.item_id, self.property_id, Date.today] )
			.order('eff_date DESC, version DESC').first
		status = ((self.deleted || self.canceled) ? 8 : 16)
		
		if current_spec		
			current_date = current_spec.eff_date
			current_version = current_spec.version

			if (self.eff_date > Date.today)
				status += 4 #pending
			elsif (self.eff_date == current_date and self.version < current_version) or self.eff_date < current_date
				status += 1 #past
			else
				status += 2 #current
			end			
		end
		
	end

	def set_version
		self.version = ((self.last_version.nil? && 0) || self.last_version) + 1
	end
	
	def last_version
		unless Specification.where(:item_id => self.item_id, :property_id => self.property_id).empty?
			Specification.where(:item_id => self.item_id, :property_id => self.property_id).order('version DESC').first.version
		end
	end
	
	def set_eff_date
		if !self.eff_date
			self.eff_date = Date.today
		end
	end

	def set_editor(user)
		self.changed_by = user
	end

	def default_values
		self.eff_date ||= Date.today
		self.string_value ||= ""
		self.text_value ||= ""
	end

	def valid_eff_date?
		if self.eff_date.blank?
			self.eff_date = Date.today
		elsif self.eff_date < Date.today
			errors.add(:eff_date, 'must be today or later')
		end
	end

	def eff_status
		s = self.status
		if 8 == s & 8
			"deleted"
		elsif 1 == s & 1
			"past"
		elsif 2 == s & 2
			"current"
		elsif 4 == s & 4
			"pending"
		end
	end

end


app/controllers/specifications_controller.rb
class SpecificationsController < ApplicationController
	include ApplicationHelper
	require 'will_paginate/array'
	before_filter :initialize_status_checkboxes, :find_items, :find_properties
	load_and_authorize_resource 

	def cancel
		@specification = Specification.find(params[:id])
		@specification.canceled = true
		@specification.set_eff_date
		@specification.set_version
		if @specification.save
			flash[:success] = "Future Item Property canceled"
			redirect_to specifications_path :item_id => @specification.item_id
		else
			redirect_to specifications_path :item_id => @specification.item_id
		end
	end

	def copy
		@specification = Specification.find(params[:id])		
		@items = Item.where("id NOT IN (?)", @specification.item_id).order(:code)
	end
	
	def create
		@new_specification = Specification.new(params[:specification])
		@new_specification.set_eff_date
		@new_specification.set_version
		@new_specification.set_editor(current_user.email)
		if @new_specification.save!
			flash[:success] = "Item Property added/changed"
			redirect_to specifications_path :item_id => params[:specification][:item_id]
		else
			render :new
		end
	end

	def destroy
		@delete_specification = @specification.dup
		@delete_specification.deleted = true
		@delete_specification.eff_date = Date.today
		@delete_specification.set_version
		@delete_specification.set_editor(current_user.email)
		if @delete_specification.save!
			flash[:success] = "Item Property deleted"
			redirect_to specifications_path :item_id => @specification.item_id
		else
			flash[:alert] = "Could not delete Item Property"
			redirect_to specifications_path :item_id => @specification.item_id
		end
	end

	def display
		@span = 12
		@items = Item.order('code')
		@display = true
		@body_class = "display"
		if params.has_key?(:item)
			@item_id = params[:item][:id]
			@item = Item.exists?(@item_id) ? Item.find(@item_id) : nil
		end	
		set_current_item
		if @item
			cookies[:item_id] = @item.id
			@specifications = Specification.includes(:property => :category).where(:item_id => @item).order("categories.display_order")
			@categories = @specifications.group_by{|is| is.property.category}		
		end
	end

	def edit
		@new_specification = @specification.dup
		@new_specification.eff_date = Date.today
		@is_edit_form = true
	end

  def index
  	@span = 12  	
		@is_table = true
  	set_list_view
  	set_visibility
		@properties = Property.order(:display_order)
		@available_properties = Property.all
		@available_items = Item.all

		if @list_for_an_item
			if params.has_key?(:specification)
				@item_id = params[:specification][:item_id]
				@item = Item.exists?(@item_id) ? Item.find(@item_id) : nil
			end
			set_current_item
	  	if @item
		  	@new_specification = Specification.new
				@specifications = Specification.visible_by_item(@item.id, @visibility).paginate(:page => params[:page], :per_page => 15) #main Specification retrieval
				@index = @specifications
				@items = Item.order(:code)				
			else
				flash[:alert] = "No items exist. Please add at least one."
				redirect_to items_path
			end
		else # @list_for_a_property
			if params.has_key?(:specification)
				@property_id = params[:specification][:property_id]
				@property = Property.exists?(@property_id) ? Property.find(@property_id) : nil
			end
			set_current_property
			if @property
				@new_specification = Specification.new
				@specifications = Specification.visible_by_property(@property.id, @visibility).paginate(:page => params[:page], :per_page => 15) #main Specification retrieval
				@index = @specifications
				@current_properties = Specification.where(:item_id => @item.id).pluck(:property_id)
				@properties = Property.where('id IN (?)', @current_properties).order(:code)				
			end
		end
  end
	
  def new
  	set_item_scope
  	if @item
	  	@current_properties = Specification.where(:item_id => @item.id).pluck(:property_id)
	  	@available_properties = Property.where('id not in (?)', @current_properties )
	  	@new_specification = Specification.new
	  end
  end

	def notes
		@specification = Specification.find(params[:id])
		@is_edit_form = true
	end

  def paste
		@specification = Specification.find(params[:id])
		@item_list = params[:copy_to][:items]
		@set_eff_date = params[:eff_date][:copy] != '1'
		ttl = 0
		success = 0
		@item_list.each do |i|
			@new_specification = @specification.dup
			@item = Item.where("code = ?", i).first
			@new_specification.item_id = @item.id
			@new_specification.eff_date = Date.today if @set_eff_date
			if @new_specification.save
				ttl += 1
				success += 1
			else
				ttl += 1
			end
		end		
		flash[:success] = "#{@specification.property.code} copied to #{success} of #{ttl} items"
		redirect_to specifications_path :item_id => @specification.item_id
	end

	def update
		if @specification.update_attributes(params[:specification])
			flash[:success] = "Notes updated"
			redirect_to specifications_path :item_id => @specification.item_id
		else
			render :notes
		end
  end

  def new_import
		logger.info "Running new_import"
  end

	def save_import
		if params[:commit] == "Import"
			Specification.import(params[:file])
		end
		redirect_to specifications_path
	end

# Utilities
	
	def find_items
		@items = Item.where(:deleted => false).order('code')
		@index = @items
	end

	def find_properties
		@properties = Property.where(:deleted => false).order('code')
		@index = @properties
	end

	def initialize_status_checkboxes
		cookies[:history] ||= "0"
		cookies[:pending] ||= "1"
		cookies[:deleted] ||= "0"
	end

	def set_item_scope
		if params[:item] && !params[:item].blank?
			@item_id = params[:item]	
		elsif params.has_key?(:specification)
			@item_id = params[:specification][:item_id]
		elsif params.has_key?(:item_id)
			@item_id = params[:item_id]
		else
			if Item.count > 0
				@item_id = Item.first.id
			else
				@item_id = nil
			end
		end
		@item = Item.exists?(@item_id) ? Item.find(@item_id) : nil
	end

	def set_list_view
  	if params.has_key?(:list_for)
	  	@list_for_an_item = params[:list_for] == "item"
	  elsif !cookies[:list_for_item].blank?
	  	@list_for_an_item = cookies[:list_for_item] == "1"
	  else
	  	@list_for_an_item = true
	  end
	  @list_for_a_property = !@list_for_an_item
	  cookies[:list_for_item] = @list_for_an_item ? "1" : "0"
	end

	def set_property_scope
		@property_id = params[:specification][:property_id]
		@property = Property.exists?(@property_id) ? Property.find(@property_id) : nil
	end

	def set_visibility
		if !params.has_key?(:specification)
  		# cookies & params are "1" or "0", @variables are true or false
			params[:show_history] = cookies[:history] == "1" ? "1" : "0" #nil
	  	params[:show_pending] = cookies[:pending] == "1" ? "1" : "0" #nil
	  	params[:show_deleted] = cookies[:deleted] == "1" ? "1" : "0" #nil
	  end
	  
  	@history = params[:show_history] #== "1"
  	@pending = params[:show_pending] #== "1"
  	@deleted = params[:show_deleted] #== "1"

  	cookies[:history] = @history #? "1" : "0"
  	cookies[:pending] = @pending #? "1" : "0"
  	cookies[:deleted] = @deleted #? "1" : "0"

	 	@visibility = @history.to_i + (@pending.to_i * 4) + (@deleted.to_i * 8) + 18
		# @visibility = (@history ? 1 : 0) + (@pending ? 4 : 0) + (@deleted ? 8 : 0) + 18
	end

end

app/views/specifications/body/_index.html.erb
	
	<tr class="<%= specification.eff_status %>">
		<% if @list_for_an_item %>
			<% if specification.property %>
				<td><%= specification.property.category.code %></td>
			<% else %>
				<td></td>
			<% end %>
			<td><%= specification.property.code %></td>
		<% else %>
			<td><%= link_to specification.item.code, specifications_path(:list_for => "item", :specification => {:item_id => specification.item.id})	%></td>
			<td><%= specification.item.name	%></td>
		<% end %>		
		<td><%= specification.text_value %></td>
		
		<td><%= specification.numeric_value %></td>
		<td><%= specification.usl %></td>
		<td><%= specification.lsl %></td>
		<td><%= specification.unit_of_measure %></td>
		
		<td class="hidden-md"><%= specification.analysis.code if specification.analysis %></td>
		<td><%= specification.eff_date %></td>
		
		<td class="hidden-md"><%= specification.eff_status %></td>
		<td class="hidden-md"><%= specification.changed_by %></td>
		<td class="centered">
			<% if specification.eff_status == 'current' %>
				<%= link_to "Edit", edit_specification_path(specification) %>
				<%= link_to "Delete",  specification, :method => :delete, :confirm => "Delete #{specification.property.code} specification for #{specification.item.code}" %>
				<%= link_to "Copy", copy_specification_path(specification), :action => :copy %>

			<% elsif specification.eff_status == 'pending' %>
				<%= link_to "Delete", cancel_specification_path(specification), :confirm => "Delete pending update of #{specification.property.code} specification for #{specification.item.code} " %>
				<%= link_to "Copy", copy_specification_path(specification), :action => :copy %>				
			<% end %>
			
			<%= link_to "Notes", notes_path(specification) %>
		</td>
	</tr>	


app/views/specifications/body/_multi_view.html.erb
<!-- loop implied by collection passed from index -->

<div class="panel panel-default">
	<div class="panel-heading">				
		<strong class="panel-title text-muted">
			<div class="row">
				<div class="<%= specification.eff_status %> col-xs-4"><%= specification.property.code %></div>
				<div class="<%= specification.eff_status %> col-xs-4"><%= specification.eff_status %></div>
				<div class="<%= specification.eff_status %> col-xs-4 text-right"><%= specification.eff_date %></div>
			</div>
		</strong>
	</div>

	<div class="panel-body">
				
		<div>	
			<% if specification.text_value != "" %>							
				<h4 class="<%= specification.eff_status %> col-xs-12 col-sm-4"><%= specification.text_value %></h4>				
			<% end %>

			<% if specification.lsl %>				
					<p class="<%= specification.eff_status %> col-xs-2 text-left"><%= specification.lsl %></p>				
			<% end %>	
	
			<% if specification.numeric_value %>				
				<h4 class="<%= specification.eff_status %> col-xs-6 text-center"><%= specification.numeric_value %></h4>				
			<% end %>

			<% if specification.usl %>				
				<p class="<%= specification.eff_status %> col-xs-2 text-right"><%= specification.usl %></p>				
			<% end %>

			<% if specification.unit_of_measure != "" %>				
					<p class="<%= specification.eff_status %> col-xs-2"><%= specification.unit_of_measure %></p>				
			<% end %>
		</div>
	</div>

		<div class="panel-footer">
			<div class="btn-group">
			
				<% if specification.eff_status == 'current' %>
					<%= link_to "Edit", edit_specification_path(specification), :class=>"btn btn-default" %>
					<%= link_to "Delete",  specification, :class=>"btn btn-default", :method => :delete, :confirm => "Delete #{specification.property.code} specification for #{specification.item.code}" %>
					
				<% elsif specification.eff_status == 'pending' %>
					<%= link_to "Delete", cancel_specification_path(specification), :class=>"btn btn-default", :confirm => "Delete pending update of #{specification.property.code} specification for #{specification.item.code}" %>				
				<% end %>
				
				<%= link_to "Notes", notes_path(specification), :class=>"btn btn-default" %>
			</div>
		</div>
	
			
</div>

app/views/specifications/body/_new.html.erb
<tr>
	<%= form_for(@new_specification) do |f| %>
		<div class="form-group">
			<% if @list_for_an_item %>
				<td></td>
				<td><%= f.collection_select :property_id, @available_properties, :id, :code, {:prompt => "Select"}, :class => "form-control input-sm" %></td>
				<%= f.hidden_field :item_id, :value => @item.id %>
			<% else %>
				<td><%= f.collection_select :item_id, @items, :id, :code, {:prompt => "Select"}, :class => "form-control input-sm" %></td>
				<td></td>
				<%= f.hidden_field :property_id, :value => @property.id %>
			<% end %>
			<td><%= f.text_field :string_value, :class => "form-control input-sm" %></td>			
			<td><%= f.text_field :numeric_value, :class => "form-control input-sm" %></td>
			<td><%= f.text_field :usl, :class => "form-control input-sm" %></td>
			<td><%= f.text_field :lsl, :class => "form-control input-sm" %></td>
			<td><%= f.text_field :unit_of_measure, :class => "form-control input-sm" %></td>		
			<td><%= f.collection_select :analysis_id, Analysis.all, :id, :code, {:prompt => :true}, :class => "form-control input-sm" %></td>
			<td class="hidden-md"><%= f.text_field :eff_date, 'data-behaviour' => 'datepicker', :class => "form-control input-sm" %></td>
			<td class="hidden-md"></td>			
			<td class="hidden-md"></td>
			<td><%= f.submit "Add Specification", :class => "btn btn-default btn-sm" %></td>
		</div>
	<% end %>
</tr>
