config/routes.rb
Factory::Application.routes.draw do

  devise_for :users, :skip => [:registrations, :sessions], :controllers => {:invitations => 'users/invitations', :registrations => 'users/registrations'}
  
  get "pages/enter"
  
  as :user do
    get "/login" => "devise/sessions#new", :as => :new_user_session
    post "/login" => "devise/sessions#create", :as => :user_session
    get "/logout" => "devise/sessions#destroy", :as => :destroy_user_session
    get "signup" => "devise/registrations#new", :as => :new_user_registration
    put "update-registration" => "users/registrations#update", :as => :user_registration
    delete "delete-registration" => "users/registrations#destroy", :as => :delete_user_registration
    get "edit-registration" => "users/registrations#edit", :as => :edit_user_registration
    get "cancel-registration" => "users/registrations#cancel", :as => :cancel_user_registration      
  end

  match 'users/:id' => 'users#destroy', :via => :delete, :as => :delete_user
	
	resources :users
  resources :imports
  resources :memberships

  resources :analyses do   
    post 'bulk_delete', :on => :collection    
  end

  resources :categories do
    collection { post :sort}
    post 'bulk_delete', :on => :collection
  end

  resources :properties do
    collection { post :sort}    
    post 'bulk_delete', :on => :collection
    collection {post :import}    
  end

  resources :items do
    post 'bulk_delete', :on => :collection
    resources :specifications
    collection {post :import}
  end

  resources :specifications do
    get 'display', :on => :collection
    get 'new_import', :on => :collection
    collection {post :save_import}
  end
  
  resources :tenants do
    get 'count', :on => :collection
    get 'set', :on => :member
  end

  resources :imports do
    collection {get :import}
  end

  match 'specifications/:id/cancel' => 'specifications#cancel', :as => :cancel_specification
  match 'specifications/:id/copy' => 'specifications#copy', :as => :copy_specification
  match 'specifications/:id/paste' => 'specifications#paste', :as => :paste_specification
  match 'specifications/:id/notes' => 'specifications#notes', :as => :notes
  match 'items/:id/copy' => 'items#copy', :as => :copy_item
  match 'analyses/:id/instructions' => 'analyses#instructions'
  match 'imports/help' => 'imports#help', :as => :import_help
  match 'about' => 'pages#about', :as => :about

  root :to => 'pages#enter'
  
end

app/models/item.rb
class Item < ActiveRecord::Base
	validates :code, :presence => true, :uniqueness => {:scope => :tenant_id} # validates uniqueness within an account
	has_many :specifications, :dependent => :destroy
	has_many :properties, :through => :specifications
	attr_accessible :code, :name
	default_scope { where(tenant_id: Tenant.current_id) }


	def available_properties
		sql_string_used_properties = "
			SELECT a.*
			FROM
				((
				SELECT property_id, MAX(version) as ver
				FROM specifications
				WHERE item_id = #{self.id}					
				GROUP BY property_id) AS y
			INNER JOIN
				(
				SELECT *
				FROM specifications
				WHERE item_id = #{self.id}
				AND deleted = false) AS z
			ON y.property_id = z.property_id
			AND y.ver = z.version)
			INNER JOIN
				(
				SELECT *
				FROM properties) AS a
			ON a.id = z.property_id
			"

		@used_properties = Property.find_by_sql(sql_string_used_properties)
		if @used_properties.empty?
			Property.all
		else
			Property.where('id NOT IN (?)', @used_properties)
		end
	end

	def copy_specifications(copy_item_id)
		item = Item.find(copy_item_id)
		specs = item.specifications
		specs.each do |s|
			spec = Specification.new(s.attributes.select{ |key, _| Specification.accessible_attributes.include? key})
			spec.item_id = self.id
			spec.version = 1
			spec.eff_date = Date.today	
			spec.save!
		end
	end

	def self.import(file)
		CSV.foreach(file.path, headers: true) do |row|
			Item.create! row.to_hash
		end
	end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
	include ApplicationHelper
	require 'will_paginate/array'
	before_filter :find_items
	before_filter :set_fluid
	load_and_authorize_resource 

	###### CRUD #######

  def index
  	logger.debug "running items.index: @current_tenant = #{@current_tenant.inspect}"
		@new_item = Item.new	
		@properties = Property.all
		@is_table = true
  end

  def edit
		@item = Item.find(params[:id])
		@is_edit_form = true
  end

  def update
		@item = Item.find(params[:id])
		@history = params[:history]
		@future = params[:future]
		if @item.update_attributes(params[:item])
			flash[:success] = "Item updated"
		else
			flash[:error] = "Unable to update item"
		end
		redirect_to items_path
  end

  def new
		@item = Item.new
  end

  def create
		@item = Item.new(params[:item])
		if @item.save
			flash[:success] = "Item added"
			cookies[:item_id] = @item.id
			if params[:include_specs]
				@item.copy_specifications(params[:copy_item_id])
				redirect_to specifications_path
			else
				redirect_to items_path
			end
		else
			flash[:error] = "Item could not be added"
			redirect_to items_path
		end
	end

  def destroy
		Item.find(params[:id]).destroy
		flash[:success] = "Item deleted"
		redirect_to items_path
  end

	###### end of CRUD #######

	def bulk_delete
		Item.destroy(params[:deletions])
		redirect_to items_path
	end

	def copy
		@copy_item = Item.find(params[:id])
		@new_item = Item.new()
		@new_item.name = @copy_item.name
		@new_item.code = @copy_item.code
		@new_item.tenant_id = @copy_item.tenant_id
		@is_edit_form = true
	end
	
	def find_items
		@items = Item.where(:deleted => false).order('code').paginate(:page => params[:page], :per_page => @per_page)
		@index = @items
	end

	def import
		Item.import(params[:file])
		redirect_to items_path
	end

	def set_fluid
		@fixed = false
	end

end

app/views/items/_new.html.erb

	<tr>
		<%= form_for(@new_item) do |f| %>
			<div class="form-group">		
				<td><%= f.text_field :code, :autofocus => true, :class => "form-control input-sm" %></td>
				<td><%= f.text_field :name, :class => "form-control input-sm" %></td>
				<td colspan="2"><%= f.submit "Submit New Item", :class => "btn btn-default btn-sm" %></td>
				<td></td>
			</div>
		<% end %>		
	</tr>

app/views/items/copy.html.erb
<% set_title "#{@copy_item.code}", prefix: "Copy " %>

<% set_width(6, 10) %>

<%= form_for @new_item do |f| %>
	<div class="row">
		<%= f.label :code, "Code", :class => "field_label" %>
		<%= f.text_field :code, :class => "text_field" %>
	</div>
		
	<div class="row bottom-space">
		<%= f.label :name, "Name", :class => "field_label" %>
		<%= f.text_field :name, :class => "text_field" %>
	</div>

	<div class="row bottom-space">
		<%= label_tag "Include Specs", :class => "checkbox" do %>
			Include All Specs
			<%= check_box_tag "include_specs", :class => "checkbox" %>
		<% end %>
	</div>

		<%= hidden_field_tag 'copy_item_id', @copy_item.id %>

	<div class="row">
		<%= f.submit "Update", :class => "btn btn-primary" %>
		<%= link_to 'Cancel', items_path, :class => "btn btn-default" %>
	</div>

<% end %>	

app/views/items/edit.html.erb
<% set_title "#{@item.code}", prefix: "Edit ", suffix: " Item" %>

<% set_width(6, 10) %>

<%= form_for @item do |f| %>
	<%= render 'layouts/body/errors', :index => @item %>
	<div class="form-group">			
		<%= f.label :name, "Code" %>
		<%= f.text_field :code, :class => "form-control" %>
	</div>

	<div class="form-group">				
		<%= f.label :name, "Name" %>
		<%= f.text_field :name, :class => "form-control" %>
	</div>

	<div class="form-group">			
		<%= f.submit :class => "btn btn-primary" %>
		<%= link_to 'Cancel', items_path, :class => "btn btn-default" %>
	</div>	

<% end %>

app/views/items/index.html.erb
<% set_title "Items" %>

<% set_width 8, 10 %>

<% content_for :thead do %>
		<tr>
			<th>Item Code</th>
			<th>Name</th>
			<th colspan="2"></th>
			<th class="col-md-1 center-block">						
				<%= link_to raw('<div class="glyphicon glyphicon-trash"></div>'), "#", :onclick => "$('.bulk_delete').submit()" %>				
			</th>
		</tr>
<% end %>

<% content_for :table do %>
	<%= render 'new' %>

	<%= form_tag bulk_delete_items_path, :method => :bulk_delete do %>
		<% @items.each do |i| %>
			<tr>
				<td><%= link_to i.code, specifications_path(i) %></td>
				<td><%= i.name %></td>
				<td><%= link_to "Edit", edit_item_path(i), :class => "pull-left" %></td>
				<td><%= link_to "Copy", copy_item_path(i), :method => :copy, :class => "pull-right" %></td>
				<td><div class="center-block"><%= check_box_tag "deletions[]", i.id %></div></td>				
			</tr>
		<% end %>
	<% end %>
<% end %>

<% content_for :import do %>	
		<%= form_tag import_items_path, :multipart => true, :class => "form-horizontal top-space" do %>
			<div class="form-group">
				<label for="file" class="col-sm-3" >Import CSV File</label> 
				<%= file_field_tag :file, :class => "col-sm-6" %>
			
				<%= submit_tag "Import", :class => "btn btn-default col-sm-3" %>
			</div>
		<% end %>	
<% end %>

<% content_for :multi_view do %>
	<% @items.each do |i| %>
		<div class="row">
			<div class="panel panel-default">
				<div class="panel-heading">				
					<strong class="panel-title text-muted"><%= i.code %></strong>
				</div>

				<div class="panel-body">						
					<div>
						<p class="text-muted col-xs-5">Name</p>
						<h4 class="col-xs-7"><%= i.name %></h4>
					</div>
				</div>
				<div class="panel-footer">
					
						<%= link_to "Edit", edit_item_path(i), :class => "btn btn-primary" %>
						
				</div>
				
			</div>
		</div>
	<% end %>
<% end %>